### PR TITLE
Add missing example output 

### PR DESCRIPTION
**Pull request by laurentkempe**

### CODE REVIEW

**Review by netwolfuk — COMMENTED** [review]
Hi @laurentkempe. Thanks for adding the screenshots.
Are you also able to add details on how one creates a webhook in teams?

Similar to https://github.com/tcplugins/tcWebHooksTemplates/blob/master/webhook-templates/stride_simple/readme.md

Thanks, Net Wolf

**Comment by laurentkempe** [comment]
@netwolfuk ok I will have a look asap

**Comment by netwolfuk** [comment]
@laurentkempe Terrific. Thanks!

**Comment by laurentkempe** [comment]
That's it @netwolfuk the installation instructions are added. Enjoy!

**Comment by netwolfuk** [comment]
Thanks @laurentkempe for your work on this. It is very much appreciated.

**Comment by laurentkempe** [comment]
Thanks @netwolfuk for your GREAT plugin

**Pull request merged**
